### ISSUE TITLE
How do i get a top bar like yours?

### ISSUE THREAD

**Issue by GiuseppeCesarano** [windozz/dotfiles#1]
I'm on xfce too

**Comment by windozz** [comment]
Literally by controlling the panel's measurements in its settings?

**Comment by GiuseppeCesarano** [comment]
Yes but, what are your panel items, and how it behave when a window is maximized

**Comment by windozz** [comment]
Maximized windows don't take up the entire screen. Use workspace margins.

**Comment by GiuseppeCesarano** [comment]
Okay, thanks you.
